name: Nuclei - Vulnerability Scan

on:
  push:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nuclei
        run: |
          # Clean up any existing nuclei files/directories
          rm -rf nuclei nuclei_3.4.10_linux_amd64.zip

          # Download and extract Nuclei
          wget -q https://github.com/projectdiscovery/nuclei/releases/download/v3.4.10/nuclei_3.4.10_linux_amd64.zip
          unzip -o nuclei_3.4.10_linux_amd64.zip

          # Install nuclei binary
          chmod +x nuclei
          sudo mv nuclei /usr/local/bin/
          nuclei -version

      - name: Run Nuclei Scan
        id: nuclei_scan
        run: |
          nuclei -target https://juice-shop.herokuapp.com -json-export nuclei.log -sarif-export nuclei.sarif

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuclei.log
          path: nuclei.log

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v3
        if: hashFiles('nuclei.sarif') != ''
        with:
          sarif_file: nuclei.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}